- name: Deploy lamp stack application
  become: yes
  become_user: root
  become_method: sudo
  hosts: all
  tasks:
    - name: Install common dependencies
      yum:
        name:
          - libselinux-python
          - libsemanage-python
          - firewalld
        state: installed

