---
- hosts: web1
  tasks:
          - name: Installing firewalld
            yum:
                    name: firewalld
                    state: present
          - name: starting and enabling firewall
            service:
                    name: firewalld
                    state: started
                    enabled: yes
