---
- hosts: web1
  tasks:
    - name: changing httpd port to 8080
      lineinfile:
            path: /etc/httpd/conf/httpd.conf
            regexp: '^Listen '
            insertafter: '^#Listen '
            line: Listen 8080 
