---
- hosts: web1
  tasks:
     - name: creating web server root file
       lineinfile:
         path: /var/www/html/index.html
         line: 'This line was added using Ansible lineinfile module!'
         create: yes

