---
- name: Start and enable httpd
  hosts: all
  gather_facts: no
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
        
    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
